### ISSUE TITLE
Write Product Overview page for uPort Credentials

### ISSUE THREAD

**Issue by pelle** [uport-project/uport-credentials#107]
We need an overview page which should live in docs/index.md see @localredhead for more details.

First version should include:

### Request and Create Verified Data for your Users

- Create and Verify Authentication Requests with users
- Request Verified Data about a user
- Verify Data about a User
- Sign Transactions for Ethereum requests

Mention that this is used primarily on the server side where keys can be stored securely. Also to use it with uport-transport for an end to end solution.

2-3 supporting paragraphs

Story will be updated with Value Prop and bullet points. Source for that will be here https://airtable.com/tbl29XEZwUhAh8tEd/viwqikXM94XKZxilg/recZeim1CI0iEsNic

**Comment by shanshokr** [comment]
Working on it here:
https://docs.google.com/document/d/1FUoLN-5CxiKhXUmfik73zhaRYCfIjRWwTqn_FeEGbpk/edit#
