### ISSUE TITLE
Add vc attribute to request JWTs

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/uport-credentials#109]
According to specs, `verReq` and `shareReq` should support `vc` attribute.

https://github.com/uport-project/specs/blob/develop/messages/verificationreq.md
https://github.com/uport-project/specs/blob/develop/messages/sharereq.md

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by rmw2** [comment]
fixed in #118
