### ISSUE TITLE
verifyDisclosure fails completely when there are multiple claims even if a single claim fails

### ISSUE THREAD

**Issue by mi-xu** [uport-project/uport-credentials#135]
**Steps to reproduce:**
- uPort mobile app holds multiple credentials with the same key (ex: nickname: 'bob', nickname: 'rob')
- App requests disclosure of credentials with key of 'nickname'
- User approve disclosure in their mobile app
- App attempts to process response by calling `credentials.verifyDisclosure()`
- If one of the claims fails verification for any reason (expired, wrong audience, malformed JWT, invalid signature, etc), the entire disclosure fails verification

**Success criteria:**
- The return object of `verifyDisclosure` should
    - contain all successfully verified claims even if a single one fails
    - contain an attribute that reports the status of any individually failed verifications

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly
