### ISSUE TITLE
createIdentity() - Buffer is not defined

### ISSUE THREAD

**Issue by miljantekic** [uport-project/uport-credentials#145]
Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

# Failure Information (for bugs)

Calling `Credentials.createIdentity()` in an environment that doesn't have `Buffer` throws an error due to `Buffer` not being defined in the `did-jwt` package. 

`uport-credentials` uses `did-jwt@0.0.7` and as I can see in `did-jwt@0.0.9` the buffer dependecy has been added to package.json and required explicitly in the file that throws the error.

Here is the commit where this was fixed:
 https://github.com/uport-project/did-jwt/commit/a7ee7dfdd9951ed51ab4cd0e66f8a53bda916d79#diff-e4e65e3648e646e8e1b2e5636b4189ff

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install `uport-credentials@1.0.2`
2. Call `Credentials.createIdentity()`

## Failure Logs/Screenshots

https://gist.github.com/miljantekic/a46aa3d7fcc13a4e1aeae7546dfdb5e8

**Comment by miljantekic** [comment]
I temporarily fixed this by using the `resolutions` property in `package.json` from yarn and rerunning `yarn install`.

**Temporary fix**

```
// package.json
{
    ...package.json content
  "resolutions": {
    "uport-credentials/did-jwt": "^0.0.9"
  }
}
```

**Comment by rmw2** [comment]
Hey @miljantekic -- thanks for the catch.  We  should be using the latest version of `did-jwt` -- I will try to get this fix out ASAP

**Comment by miljantekic** [comment]
@rmw2 Np, thanks for the quick reply :)
