### ISSUE TITLE
JWT is not valid yet (issued in the future)

### ISSUE THREAD

**Issue by z3us94** [uport-project/uport-credentials#151]
verifyDisclosure() method throws me this error "JWT is not valid yet (issued in the future)", when a token comes from a device where the time is ahead of the server time. Is there a workaround for this?

**Comment by rmw2** [comment]
hi @z3us94 -- This happens when the skew between the clock of your mobile device and the machine verifying the signature is larger than the `IAT_SKEW` constant defined in the `did-jwt` dependency.  This was changed from 60s to 5minutes within the last few months -- fixes include ensuring  your packages are up to date to use the larger skew tolerance, and if the problem persists, fixing the clock skew on your mobile device.  Depending on the operating system, a device restart often helps.

**Comment by z3us94** [comment]
Hey, @rmw2  thank you for the quick response. Yeah, I tried updating the version and setting the time zone directly of my devices instead of manipulating time. So I guess it's not working when we manipulate the time of the device without changing the correct timezone which is okay since that is not a correct scenario.

**Comment by vongohren** [comment]
@rmw2 so from a user experience point of view, you suggest that we shall be able to return a message to the user that their time might be a bit skewed?
Im just trying to figure out how to convey the message to the user, because we as developers understand and dont care, but users care :D

**Comment by rmw2** [comment]
Great point @vongohren -- as it stands now there's no way on the mobile app to catch a situation in which it fails to verify a JWT with a future timestamp.  I'm not sure how quickly we can implement a new UX for this situation, but my guess as to the best way to mitigate it would be to warn users about the possibility of clocks being out of sync, and/or set a timeout on a request to prompt them with troubleshooting help. 

I'll loop in @jasonhealy and @simonas-notcat to see if it would be feasible to at least edit the error message to be more user friendly -- maybe something along the lines of "This message appears to have been issued in the future.  For your security, please make sure your clock is accurate." and maybe a link to info about how to reset/resync a mobile device clock?

**Comment by z3us94** [comment]
@vongohren yeah the above error throws from the JWT decoder that the verifyDisclosure() method make use of. So yeah we could have a catch and give the user a proper message since we are now sure of what is the cause of this.

**Comment by vongohren** [comment]
Perfect shehan, then we can look into that at a later date, but the task
tracks this issue so we will see it at some point.

**Comment by mirceanis** [comment]
Is this still an issue?
If so, there is a workaround you can try which is to not have an issuance date at all in the JWT.
You should be able to do it by setting `iat : undefined` in the payload you send to `signJWT`

**Comment by vongohren** [comment]
@mirceanis thanks for the feedback. It is not something we continued to experience in our setup, but I believe it was not an effort to fix it on either side. So this workaround is something I will note for future reference. But unless you guys think to track this to fix it, you can close it

**Comment by mirceanis** [comment]
There isn't any plan to fix it since dealing with clock sync between devices is out of scope for this lib.
The same override with `iat` can be used for setting a precomputed issuance date in case such a scenario comes up.

Thanks, closing this now.
