### ISSUE TITLE
Sample code not working

### ISSUE THREAD

**Issue by only1sham** [uport-project/uport-credentials#196]
This code is not working due to the breaking changes in 'ethr-did-resolver' library. Please provide the working sample for creating and verifying disclosure request and credentials.

**Comment by justinmchase** [comment]
I came here to report this also.

As of the version 1.3.0 update this no longer works:
https://github.com/uport-project/uport-credentials/blob/develop/docs/guides/index.md#configure-your-application

And the small example on the main readme is incomplete, for example the SimpleSinger is not imported so its hard to know where its supposed to be imported from.
https://github.com/uport-project/uport-credentials#uport-credentials-library

**Comment by mirceanis** [comment]
@justinmchase, @only1sham, thank you for reporting this.
Please take a look at the updated sample code and see if that fixes it for you.
