### ISSUE TITLE
Support issueing and requesting VCs

### ISSUE THREAD

**Issue by PeterTheOne** [uport-project/uport-credentials#248]
**Is your feature request related to a problem? Please describe.**
I'd like to issue Verifiable Credentials starting from a `CredentialPayload` like in `did-jwt-vc` and I'd like to create a `DisclosureRequest` (and DisclosureResponse?) for a Verifiable Credential.

**Describe the solution you'd like**
Have some functions that create VCs and request VCs.

**Describe alternatives you've considered**
Creating Verifiable Credentials with `did-jwt-vc` works, but may be less convenient if one is already using `uport-credentials`. But how does one request VCs?

**Comment by PeterTheOne** [comment]
It could be implemented similiar to the Jolocom example referred to in https://github.com/WebOfTrustInfo/rwot6-santabarbara/blob/master/final-documents/did-auth.md#jwt-format .

**Comment by PeterTheOne** [comment]
Claims seem to be requestable with the `verified` array parameter.

**Comment by PeterTheOne** [comment]
> I'd like to issue Verifiable Credentials starting from a CredentialPayload like in did-jwt-vc ...

This part should be fixed with https://github.com/uport-project/uport-credentials/pull/257 .

**Comment by mirceanis** [comment]
@PeterTheOne, now that #257 is merged, what else is needed?

Can you give an example of the API you envision?

**Comment by PeterTheOne** [comment]
https://github.com/decentralized-identity/papers/blob/master/Credential%20Exchange%20Message%20Formats%20Survey.md
