### ISSUE TITLE
As a developer with existing users I want to support new EthrDID identities without changing my code

### ISSUE THREAD

**Issue by pelle** [uport-project/uport-credentials#70]
This has to be fully backwards compatible for most users. Do not add support for `EthrDID` app identities. New developers should use the breaking changes of the libraries.

- [x] Start from `develop`
- [x] Only support MNID app identities
- [x] Exactly the same configuration parameters as existing version of libraries
- [x] Backport configuration from`did` branch
- [x] Backport `requestDisclosure()` from `did` branch into `createRequest()`
- [x] Change `receive()` to use `authenticate()` from `did` branch (also copy over `processDisclosurePayload`)
- [x] Change `push()` to use the correct pututu url depending on the DID
- [x] Create new `createJWT()` and `verifyJWT()` functions that simply wrap around the ones in DID-JWT, but change the function signature to match the old ones
- [x] Make sure tests pass. It may be easier to copy tests over from the ones in the `did` branch as they are designed to work with DID-JWT

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by pelle** [comment]
I don't think it is necessary to use transports library. Continue to use the existing push function.

**Comment by rmw2** [comment]
Delivered in v0.7.0
