### ISSUE TITLE
Unable to push notifications to Android device

### ISSUE THREAD

**Issue by subhasisbanik** [uport-project/uport-credentials#76]
I am trying to push notification to user with: 
https://github.com/uport-project/uport-js/blob/develop/docs/reference/index.md#credentialspushtoken-payload-pubenckey--promiseobject-error
I have added payload object with url and message(a simple string) and public Enc Key received by the user.
 I am getting warning from the server : 
"WARNING: Calling push without a public encryption key is deprecated"

Also I am receiving the text in my mobile device, but when tapping onto it, I am getting blank screen. 

Please help...

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by cmditch** [comment]
The documentation has the argument order flipped, and other tutorials I have seen around now seem to be outdated.

The code is the point of truth as it stands: https://github.com/uport-project/uport-js/blob/develop/src/Credentials.js#L239

I'm also having trouble with push notifications. I get them showing up on my phone (iPhone), but the uPort mobile app displays them as a blank white screen and freezes up.

**Comment by mirceanis** [comment]
Looks like the messages arrive but the app is unable to react properly.
Is this still an issue?
